import { gcode } from 'react-syntax-highlighter/dist/esm/languages/prism';
import { PrismLight } from 'react-syntax-highlighter';

// Register language for GCode syntax highlighting
PrismLight.registerLanguage('gcode', gcode);

export const vsCodeLightTheme = {
  'code[class*="language-"]': {
    color: '#222222',
    background: 'transparent',
    textShadow: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '0.9em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#222222',
    background: '#f3f6f6',
    textShadow: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '0.9em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    tabSize: '4',
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
    border: '1px solid #e1e4e5',
    borderRadius: '4px',
  },
  'comment': { color: '#408080', fontStyle: 'italic' },
  'property': { color: '#008000' },
  'tag': { color: '#000080' },
  'boolean': { color: '#000080' },
  'number': { color: '#000080' },
  'constant': { color: '#000080' },
  'symbol': { color: '#000080' },
  'string': { color: '#BA2121' },
  'selector': { color: '#000080' },
  'attr-name': { color: '#008000' },
  'entity': { cursor: 'help' },
  'url': { color: '#0000FF' },
  'keyword': { color: '#008000', fontWeight: 'bold' },
  'builtin': { color: '#008000' },
  'function': { color: '#0000FF' },
  'operator': { color: '#AA22FF', fontWeight: 'bold' }
};

export const vsCodeDarkTheme = {
  'code[class*="language-"]': {
    color: '#D4D4D4',
    background: 'transparent',
    textShadow: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#D4D4D4',
    background: '#1E1E1E',
    textShadow: 'none',
    fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
    fontSize: '1em',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.5',
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    padding: '1em',
    margin: '.5em 0',
    overflow: 'auto',
  },
  'pre code': {
    background: 'none',
    fontSize: '1em',
  },
  ':not(pre) > code[class*="language-"]': {
    background: '#1E1E1E',
    padding: '.1em',
    borderRadius: '.3em',
    whiteSpace: 'normal',
  },
  'comment': { color: '#6A9955' },
  'prolog': { color: '#6A9955' },
  'doctype': { color: '#6A9955' },
  'cdata': { color: '#6A9955' },
  'punctuation': { color: '#D4D4D4' },
  'namespace': { opacity: '.7' },
  'property': { color: '#9CDCFE' },
  'tag': { color: '#569CD6' },
  'boolean': { color: '#569CD6' },
  'number': { color: '#B5CEA8' },
  'constant': { color: '#9CDCFE' },
  'symbol': { color: '#9CDCFE' },
  'selector': { color: '#569CD6' },
  'attr-name': { color: '#9CDCFE' },
  'string': { color: '#CE9178' },
  'char': { color: '#9CDCFE' },
  'builtin': { color: '#569CD6' },
  'inserted': { color: '#B5CEA8', backgroundColor: '#144212' },
  'operator': { color: '#D4D4D4' },
  'entity': {
    cursor: 'help',
    backgroundColor: '#00000010',
  },
  'url': {
    color: '#9CDCFE',
  },
  '.language-css .token.string': {
    color: '#569CD6',
  },
  '.style .token.string': {
    color: '#569CD6',
  },
  'keyword': { color: '#569CD6' }
};
